### ISSUE TITLE
TypeError: Failed to execute 'decode' on 'TextDecoder': The encoded data was not valid.

### ISSUE THREAD

**Issue by Jack-rainbow** [zhangyuang/v8-profiler-rs#2]
## 问题步骤
1.本公司系统导出了一份86MB的内存快照文件
2.上传内存快照文件
3.等待绘制
4.报错TypeError: Failed to execute 'decode' on 'TextDecoder': The encoded data was not valid.

## 问题原因
未知

## 系统
mac 12.4
safari 版本15.5 (17613.2.7.1.8)

## 期望
期望正常展示节点

## 其他信息
暂无

**Comment by zhangyuang** [comment]
换个浏览器比如firefox呢

**Comment by Jack-rainbow** [comment]
> 换个浏览器比如firefox呢

我先使用其他平台快照，去做这个demo熟悉吧，谢谢您的回复。

**Comment by zhangyuang** [comment]
方便的话可扫码加好友提供原文件给我看看

**Comment by Jack-rainbow** [comment]
> 方便的话可扫码加好友提供原文件给我看看

v私。

**Comment by zhangyuang** [comment]
目前针对大文件的去看目前新增二进制文件支持本地解析后上传分析。后续会进一步优化内存空间和解析性能
