### ISSUE TITLE
网站又不能访问了 

### ISSUE THREAD

**Issue by HardenSG** [zhangyuang/v8-profiler-rs#5]
网站又不能访问了

**Comment by zhangyuang** [comment]
测试可以正常访问，DNS服务是托管在cloudflare上，可以检查自身的网络服务商是否能够正常访问cloudflare

**Comment by zhangyuang** [comment]
又更新了一下 再试试

**Comment by HardenSG** [comment]
> 又更新了一下 再试试

可以了可以了，可能刚刚内网不能访问。（好快的恢复速度，感谢！
